Repository npgsql/efcore.pg, pull requests merged in 2018-10, with the labels that each got.

#671 Consolidate string method call translators
  src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlCompositeMethodCallTranslator.cs
  src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlStringContainsTranslator.cs
  src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlStringEndsWithTranslator.cs
  src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlStringIndexOfTranslator.cs
  src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlStringIsNullOrWhiteSpaceTranslator.cs
  src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlStringReplaceTranslator.cs
  src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlStringStartsWithTranslator.cs
  src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlStringSubstringTranslator.cs
  src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlStringTranslator.cs
  src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlStringTrimEndTranslator.cs
  src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlStringTrimStartTranslator.cs
  src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlStringTrimTranslator.cs
Labels: refactor

#673 Translate {PadLeft,PadRight} to {lpad,rpad}
  src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlStringTranslator.cs
  test/EFCore.PG.FunctionalTests/Query/SimpleQueryNpgsqlTest.cs
Labels: enhancement

#655 Fixing docs between master and dev
  doc/index.md
  doc/mapping/enum.md
  doc/mapping/full-text-search.md
  doc/mapping/general.md
  doc/mapping/range.md
  doc/misc.md
  doc/miscellaneous.md
  doc/release-notes/2.0.md
  doc/release-notes/2.1.md
  doc/release-notes/2.2.md
  doc/toc.md
  doc/value-generation.md
Labels: doc

#677 Use generic `MapRange` in docs
  doc/mapping/range.md
Labels: doc

#605 Update enum quoting and default schema use
  src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs
  src/EFCore.PG/Storage/Internal/Mapping/NpgsqlEnumTypeMapping.cs
  src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs
  test/EFCore.PG.FunctionalTests/Query/EnumQueryTest.cs
  test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingTest.cs
Labels: bug

#672 Switch to new EF Core plugin model
  .gitignore
  src/EFCore.PG.NTS/Design/Internal/NpgsqlNetTopologySuiteDesignTimeServices.cs
  src/EFCore.PG.NTS/EFCore.PG.NTS.csproj
  src/EFCore.PG.NTS/Extensions/NpgsqlNetTopologySuiteDbContextOptionsBuilderExtensions.cs
  src/EFCore.PG.NTS/Extensions/NpgsqlNetTopologySuiteServiceCollectionExtensions.cs
  src/EFCore.PG.NTS/Infrastructure/Internal/INpgsqlNetTopologySuiteOptions.cs
  src/EFCore.PG.NTS/Infrastructure/Internal/NpgsqlNetTopologySuiteOptionsExtension.cs
  src/EFCore.PG.NTS/Internal/NpgsqlNetTopologySuiteOptions.cs
  src/EFCore.PG.NTS/NetTopologySuiteDbContextOptionsExtensions.cs
  src/EFCore.PG.NTS/NetTopologySuiteGeographyTypeMapping.cs
  src/EFCore.PG.NTS/NetTopologySuiteGeometryTypeMapping.cs
  src/EFCore.PG.NTS/NetTopologySuitePlugin.cs
  src/EFCore.PG.NTS/Query/ExpressionTranslators/Internal/NpgsqlNetTopologySuiteMemberTranslatorPlugin.cs
  src/EFCore.PG.NTS/Query/ExpressionTranslators/Internal/NpgsqlNetTopologySuiteMethodCallTranslatorPlugin.cs
  src/EFCore.PG.NTS/Storage/Internal/NpgsqlGeometryTypeMapping.cs
  src/EFCore.PG.NTS/Storage/Internal/NpgsqlNetTopologySuiteTypeMappingSourcePlugin.cs
  src/EFCore.PG.NTS/build/netstandard2.0/Npgsql.EntityFrameworkCore.PostgreSQL.NetTopologySuite.targets
  src/EFCore.PG.NodaTime/Design/Internal/NpgsqlNodaTimeDesignTimeServices.cs
  src/EFCore.PG.NodaTime/EFCore.PG.NodaTime.csproj
  src/EFCore.PG.NodaTime/Extensions/NpgsqlNodaTimeDbContextOptionsBuilderExtensions.cs
  src/EFCore.PG.NodaTime/Extensions/NpgsqlNodaTimeServiceCollectionExtensions.cs
  src/EFCore.PG.NodaTime/Infrastructure/Internal/NpgsqlNodaTimeOptionsExtension.cs
  src/EFCore.PG.NodaTime/NodaTimeDbContextOptionsExtensions.cs
  src/EFCore.PG.NodaTime/NodaTimePlugin.cs
  src/EFCore.PG.NodaTime/Query/ExpressionTranslators/Internal/NpgsqlNodaTimeMemberTranslatorPlugin.cs
  src/EFCore.PG.NodaTime/Query/ExpressionTranslators/Internal/NpgsqlNodaTimeMethodCallTranslatorPlugin.cs
  src/EFCore.PG.NodaTime/Storage/Internal/NodaTimeMappings.cs
  src/EFCore.PG.NodaTime/Storage/Internal/NpgsqlNodaTimeTypeMappingSourcePlugin.cs
  src/EFCore.PG.NodaTime/build/netstandard2.0/Npgsql.EntityFrameworkCore.PostgreSQL.NodaTime.targets
  src/EFCore.PG/Infrastructure/Internal/INpgsqlOptions.cs
  src/EFCore.PG/Infrastructure/Internal/NpgsqlOptionsExtension.cs
  src/EFCore.PG/Infrastructure/NpgsqlDbContextOptionsBuilder.cs
  src/EFCore.PG/Infrastructure/NpgsqlEntityFrameworkPlugin.cs
  src/EFCore.PG/Internal/NpgsqlOptions.cs
  src/EFCore.PG/Query/EvaluatableExpressionFilters/Internal/NpgsqlCompositeEvaluatableExpressionFilter.cs
  src/EFCore.PG/Query/EvaluatableExpressionFilters/Internal/NpgsqlNodaTimeEvaluatableExpressionFilter.cs
  src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlCompositeMemberTranslator.cs
  src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlCompositeMethodCallTranslator.cs
  src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs
  src/Shared/MemberInfoExtensions.cs
  test/EFCore.PG.FunctionalTests/EFCore.PG.FunctionalTests.csproj
  test/EFCore.PG.FunctionalTests/NpgsqlComplianceTest.cs
  test/EFCore.PG.FunctionalTests/Query/SpatialQueryNpgsqlGeographyFixture.cs
  test/EFCore.PG.FunctionalTests/Query/SpatialQueryNpgsqlGeographyTest.cs
  test/EFCore.PG.FunctionalTests/Query/SpatialQueryNpgsqlGeometryFixture.cs
  test/EFCore.PG.FunctionalTests/Query/SpatialQueryNpgsqlGeometryTest.cs
  test/EFCore.PG.FunctionalTests/SpatialNpgsqlFixture.cs
  test/EFCore.PG.FunctionalTests/SpatialNpgsqlTest.cs
  test/EFCore.PG.Plugins.FunctionalTests/NetTopologySuiteTest.cs
  test/EFCore.PG.Plugins.FunctionalTests/NodaTimeQueryNpgsqlTest.cs
  test/EFCore.PG.Plugins.FunctionalTests/NpgsqlNodaTimeTypeMappingTest.cs
Labels: enhancement, refactor
