Repository npgsql/efcore.pg, pull requests merged in 2018-08, with the labels that each got.

#560 Update range operator docs
  doc/mapping/range.md
Labels: doc

#571 Drop IComparable<T> constraint for range extensions
  src/EFCore.PG/Extensions/NpgsqlRangeExtensions.cs
Labels: bug

#589 Translate Period.FromXXX()
  src/EFCore.PG.NodaTime/NodaTimeMethodCallTranslator.cs
  test/EFCore.PG.Plugins.FunctionalTests/NodaTimeTest.cs
Labels: enhancement

#598 Add doc comments to NpgsqlCodeGenerator
  src/EFCore.PG/Scaffolding/Internal/NpgsqlCodeGenerator.cs
Labels: refactor

#591 Refactor DateTime member translator for plugins
  src/EFCore.PG.NodaTime/NodaTimeMemberTranslator.cs
  src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlDateTimeMemberTranslator.cs
Labels: refactor

#599 Refactor and document NpgsqlDatabaseModelFactory (1)
  src/EFCore.PG/Scaffolding/Internal/NpgsqlDatabaseModelFactory.cs
Labels: refactor

#604 Translate DateTime.Today
  src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlDateTimeMemberTranslator.cs
  test/EFCore.PG.FunctionalTests/Query/SimpleQueryNpgsqlTest.Where.cs
Labels: enhancement

#600 Refactor and document NpgsqlDatabaseModelFactory (2)
  src/EFCore.PG/Scaffolding/Internal/NpgsqlDatabaseModelFactory.cs
Labels: refactor

#601 Refactor and document NpgsqlDatabaseModelFactory (3)
  src/EFCore.PG/Scaffolding/Internal/NpgsqlDatabaseModelFactory.cs
Labels: refactor

#602 Refactor and document NpgsqlDatabaseModelFactory (4)
  src/EFCore.PG/Scaffolding/Internal/NpgsqlDatabaseModelFactory.cs
Labels: refactor

#606 Translate GREATEST(...) and LEAST(...)
  src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlCompositeMethodCallTranslator.cs
  src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlMathTranslator.cs
  test/EFCore.PG.FunctionalTests/Query/MathQueryTest.cs
Labels: enhancement

#612 Inject compatibility version for migrations
  src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs
Labels: enhancement

#608 Support user-defined ranges
  doc/mapping/range.md
  doc/release-notes/2.2.md
  doc/toc.md
  src/EFCore.PG.NodaTime/NodaTimePlugin.cs
  src/EFCore.PG/Extensions/NpgsqlModelBuilderExtensions.cs
  src/EFCore.PG/Infrastructure/Internal/INpgsqlOptions.cs
  src/EFCore.PG/Infrastructure/Internal/NpgsqlOptionsExtension.cs
  src/EFCore.PG/Infrastructure/NpgsqlDbContextOptionsBuilder.cs
  src/EFCore.PG/Internal/NpgsqlOptions.cs
  src/EFCore.PG/Metadata/Internal/NpgsqlAnnotationNames.cs
  src/EFCore.PG/Metadata/NpgsqlModelAnnotations.cs
  src/EFCore.PG/Metadata/PostgresEnum.cs
  src/EFCore.PG/Metadata/PostgresRange.cs
  src/EFCore.PG/Migrations/Internal/NpgsqlMigrationsAnnotationProvider.cs
  src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs
  src/EFCore.PG/Storage/Internal/Mapping/NpgsqlRangeTypeMapping.cs
  src/EFCore.PG/Storage/Internal/NpgsqlDatabaseCreator.cs
  src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs
  test/EFCore.PG.FunctionalTests/Query/RangeQueryNpgsqlTest.cs
Labels: enhancement

#610 Simplify type mapping clone methods
  src/EFCore.PG/Storage/Internal/Mapping/NpgsqlArrayTypeMapping.cs
  src/EFCore.PG/Storage/Internal/Mapping/NpgsqlBitTypeMapping.cs
  src/EFCore.PG/Storage/Internal/Mapping/NpgsqlBoolTypeMapping.cs
  src/EFCore.PG/Storage/Internal/Mapping/NpgsqlByteArrayTypeMapping.cs
  src/EFCore.PG/Storage/Internal/Mapping/NpgsqlCitextTypeMapping.cs
  src/EFCore.PG/Storage/Internal/Mapping/NpgsqlDateTimeTypeMappings.cs
  src/EFCore.PG/Storage/Internal/Mapping/NpgsqlEnumTypeMapping.cs
  src/EFCore.PG/Storage/Internal/Mapping/NpgsqlGeometricTypeMapping.cs
  src/EFCore.PG/Storage/Internal/Mapping/NpgsqlHstoreTypeMapping.cs
  src/EFCore.PG/Storage/Internal/Mapping/NpgsqlJsonTypeMapping.cs
  src/EFCore.PG/Storage/Internal/Mapping/NpgsqlJsonbTypeMapping.cs
  src/EFCore.PG/Storage/Internal/Mapping/NpgsqlListTypeMapping.cs
  src/EFCore.PG/Storage/Internal/Mapping/NpgsqlNetworkTypeMappings.cs
  src/EFCore.PG/Storage/Internal/Mapping/NpgsqlRangeTypeMapping.cs
  src/EFCore.PG/Storage/Internal/Mapping/NpgsqlRegconfigTypeMapping.cs
  src/EFCore.PG/Storage/Internal/Mapping/NpgsqlStringTypeMapping.cs
  src/EFCore.PG/Storage/Internal/Mapping/NpgsqlTidTypeMapping.cs
  src/EFCore.PG/Storage/Internal/Mapping/NpgsqlTsQueryTypeMapping.cs
  src/EFCore.PG/Storage/Internal/Mapping/NpgsqlTsRankingNormalizationTypeMapping.cs
  src/EFCore.PG/Storage/Internal/Mapping/NpgsqlTsVectorMapping.cs
  src/EFCore.PG/Storage/Internal/Mapping/NpgsqlUIntTypeMapping.cs
  src/EFCore.PG/Storage/Internal/Mapping/NpgsqlVarbitTypeMapping.cs
  src/EFCore.PG/Storage/Internal/Mapping/NpgsqlXmlTypeMapping.cs
Labels: refactor

#615 Cleanup style and document public API surfaces
  src/EFCore.PG.NTS/NetTopologySuiteMethodCallTranslator.cs
  src/EFCore.PG/Extensions/NpgsqlDbFunctionsExtensions.cs
  src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlConvertTranslator.cs
  src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlDateAddTranslator.cs
  src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlFullTextSearchMethodTranslator.cs
  src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlLikeTranslator.cs
  src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlRegexIsMatchTranslator.cs
  src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlStringContainsTranslator.cs
  src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlStringEndsWithTranslator.cs
  src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlStringIndexOfTranslator.cs
  src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlStringIsNullOrWhiteSpaceTranslator.cs
  src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlStringLengthTranslator.cs
  src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlStringReplaceTranslator.cs
  src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlStringStartsWithTranslator.cs
  src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlStringSubstringTranslator.cs
  src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlStringTrimTranslator.cs
  src/EFCore.PG/Query/ExpressionVisitors/NpgsqlSqlTranslatingExpressionVisitor.cs
Labels: refactor

#588 Update mapping for character(n)
  src/EFCore.PG/Storage/Internal/Mapping/NpgsqlCharacterTypeMapping.cs
  src/EFCore.PG/Storage/Internal/Mapping/NpgsqlStringTypeMapping.cs
  src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs
  test/EFCore.PG.FunctionalTests/Query/CharacterQueryNpgsqlTest.cs
Labels: bug
