Repository npgsql/efcore.pg, pull requests merged in 2018-11, with the labels that each got.

#691 Simplified building of SQL literals
  src/EFCore.PG/Storage/Internal/Mapping/NpgsqlGeometricTypeMapping.cs
Labels: refactor

#662 Add support for index operators
  src/EFCore.PG/Design/Internal/NpgsqlAnnotationCodeGenerator.cs
  src/EFCore.PG/Extensions/NpgsqlIndexBuilderExtensions.cs
  src/EFCore.PG/Metadata/INpgsqlIndexAnnotations.cs
  src/EFCore.PG/Metadata/Internal/NpgsqlAnnotationNames.cs
  src/EFCore.PG/Metadata/NpgsqlIndexAnnotations.cs
  src/EFCore.PG/Migrations/Internal/NpgsqlMigrationsAnnotationProvider.cs
  src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs
  src/EFCore.PG/Utilities/Check.cs
  test/EFCore.PG.FunctionalTests/NpgsqlMigrationSqlGeneratorTest.cs
Labels: enhancement

#699 Add support for INCLUDE clause in indexes
  src/EFCore.PG/Design/Internal/NpgsqlAnnotationCodeGenerator.cs
  src/EFCore.PG/Extensions/NpgsqlEntityTypeBuilderExtensions.cs
  src/EFCore.PG/Extensions/NpgsqlIndexBuilderExtensions.cs
  src/EFCore.PG/Metadata/INpgsqlIndexAnnotations.cs
  src/EFCore.PG/Metadata/Internal/NpgsqlAnnotationNames.cs
  src/EFCore.PG/Metadata/NpgsqlIndexAnnotations.cs
  src/EFCore.PG/Migrations/Internal/NpgsqlMigrationsAnnotationProvider.cs
  src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs
  test/EFCore.PG.FunctionalTests/NpgsqlMigrationSqlGeneratorTest.cs
Labels: enhancement

#703 Prefer `PgNameAttribute` in `NpgsqlEnumTypeMapping`
  src/EFCore.PG/Storage/Internal/Mapping/NpgsqlEnumTypeMapping.cs
  test/EFCore.PG.FunctionalTests/Query/EnumQueryTest.cs
Labels: bug

#709 Scaffold index operators and included (covered) index columns
  src/EFCore.PG/Scaffolding/Internal/NpgsqlDatabaseModelFactory.cs
  test/EFCore.PG.FunctionalTests/Scaffolding/NpgsqlDatabaseModelFactoryTest.cs
  test/EFCore.PG.FunctionalTests/TestUtilities/NpgsqlTestStore.cs
Labels: enhancement

#706 Translate `Guid.NewGuid()` as `uuid_generate_v4()`
  src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlCompositeMethodCallTranslator.cs
  src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlGuidTranslator.cs
  test/EFCore.PG.FunctionalTests/Northwind.sql
  test/EFCore.PG.FunctionalTests/Query/NorthwindQueryNpgsqlFixture.cs
  test/EFCore.PG.FunctionalTests/Query/SimpleQueryNpgsqlTest.Functions.cs
  test/EFCore.PG.FunctionalTests/SpatialNpgsqlFixture.cs
Labels: enhancement

#626 Update range mapping for schema-qualified and quoted ranges
  src/EFCore.PG.NodaTime/Storage/Internal/NpgsqlNodaTimeTypeMappingSourcePlugin.cs
  src/EFCore.PG/Design/Internal/NpgsqlAnnotationCodeGenerator.cs
  src/EFCore.PG/Infrastructure/Internal/NpgsqlOptionsExtension.cs
  src/EFCore.PG/Infrastructure/NpgsqlDbContextOptionsBuilder.cs
  src/EFCore.PG/Metadata/PostgresRange.cs
  src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs
  src/EFCore.PG/Storage/Internal/Mapping/NpgsqlRangeTypeMapping.cs
  src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs
  test/EFCore.PG.FunctionalTests/Query/RangeQueryNpgsqlTest.cs
  test/EFCore.PG.FunctionalTests/Scaffolding/NpgsqlDatabaseModelFactoryTest.cs
  test/EFCore.PG.Plugins.FunctionalTests/NpgsqlNodaTimeTypeMappingTest.cs
  test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingSourceTest.cs
  test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingTest.cs
  test/EFCore.PG.Tests/Update/NpgsqlModificationCommandBatchFactoryTest.cs
  test/EFCore.PG.Tests/Update/NpgsqlModificationCommandBatchTest.cs
Labels: enhancement

#716 Refactor to use annotation access pattern
  src/EFCore.PG/Extensions/NpgsqlMetadataExtensions.cs
  src/EFCore.PG/Metadata/INpgsqlModelAnnotations.cs
  src/EFCore.PG/Metadata/NpgsqlAlterDatabaseOperationAnnotations.cs
  src/EFCore.PG/Metadata/NpgsqlDatabaseModelAnnotations.cs
  src/EFCore.PG/Metadata/NpgsqlModelAnnotations.cs
  src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs
  src/EFCore.PG/Storage/Internal/NpgsqlDatabaseCreator.cs
  test/EFCore.PG.FunctionalTests/Scaffolding/NpgsqlDatabaseModelFactoryTest.cs
  test/EFCore.PG.FunctionalTests/TestUtilities/NpgsqlDatabaseCleaner.cs
Labels: refactor

#724 Schema enums follow up (part 1)
  src/EFCore.PG/Storage/Internal/Mapping/NpgsqlEnumTypeMapping.cs
  src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs
  test/EFCore.PG.FunctionalTests/BuiltInDataTypesNpgsqlTest.cs
  test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingTest.cs
Labels: refactor

#726 Simplify annotation provider (from 718)
  src/EFCore.PG/Metadata/INpgsqlPropertyAnnotations.cs
  src/EFCore.PG/Migrations/Internal/NpgsqlMigrationsAnnotationProvider.cs
Labels: refactor
