Repository npgsql/efcore.pg, pull requests merged in 2019-01, with the labels that each got.

#784 Correct DbContext class name in documentation
  doc/index.md
Labels: doc

#781 Cleanup unit test warnings
  EFCore.PG.sln.DotSettings
  test/EFCore.PG.Tests/Metadata/NpgsqlInternalMetadataBuilderExtensionsTest.cs
  test/EFCore.PG.Tests/Metadata/NpgsqlMetadataExtensionsTest.cs
  test/EFCore.PG.Tests/NpgsqlDatabaseFacadeTest.cs
  test/EFCore.PG.Tests/NpgsqlValueGeneratorSelectorTest.cs
  test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingTest.cs
  test/EFCore.PG.Tests/TestUtilities/FakeInterceptingLogger.cs
Labels: refactor

#786 Add xmldocs for various public members
  src/EFCore.PG/Design/Internal/NpgsqlDesignTimeServices.cs
  src/EFCore.PG/Diagnostics/NpgsqlEventId.cs
  src/EFCore.PG/Storage/Internal/Mapping/NpgsqlArrayTypeMapping.cs
  src/EFCore.PG/Storage/Internal/Mapping/NpgsqlBitTypeMapping.cs
  src/EFCore.PG/Storage/Internal/Mapping/NpgsqlHstoreTypeMapping.cs
  src/EFCore.PG/Storage/Internal/Mapping/NpgsqlListTypeMapping.cs
  src/EFCore.PG/Storage/Internal/Mapping/NpgsqlNetworkTypeMappings.cs
  src/EFCore.PG/Storage/Internal/Mapping/NpgsqlRangeTypeMapping.cs
  src/EFCore.PG/Storage/Internal/Mapping/NpgsqlTypeMapping.cs
  src/EFCore.PG/Update/Internal/NpgsqlModificationCommandBatch.cs
Labels: refactor

#783 Cleanup plugin test warnings
  test/EFCore.PG.Plugins.FunctionalTests/NodaTimeQueryNpgsqlTest.cs
  test/EFCore.PG.Plugins.FunctionalTests/NpgsqlNodaTimeTypeMappingTest.cs
Labels: refactor

#782 Cleanup functional test warnings
  test/EFCore.PG.FunctionalTests/BatchingTest.cs
  test/EFCore.PG.FunctionalTests/BuiltInDataTypesNpgsqlTest.cs
  test/EFCore.PG.FunctionalTests/ConnectionSpecificationTest.cs
  test/EFCore.PG.FunctionalTests/ConvertToProviderTypesNpgsqlTest.cs
  test/EFCore.PG.FunctionalTests/DefaultValuesTest.cs
  test/EFCore.PG.FunctionalTests/ExecutionStrategyTest.cs
  test/EFCore.PG.FunctionalTests/ExistingConnectionTest.cs
  test/EFCore.PG.FunctionalTests/LazyLoadProxySqlNpgsqlTest.cs
  test/EFCore.PG.FunctionalTests/LoadNpgsqlTest.cs
  test/EFCore.PG.FunctionalTests/MigrationsNpgsqlTest.cs
  test/EFCore.PG.FunctionalTests/NpgsqlDatabaseCreatorTest.cs
  test/EFCore.PG.FunctionalTests/Query/AsyncGearsOfWarQueryNpgsqlTest.cs
  test/EFCore.PG.FunctionalTests/Query/AsyncIncludeNpgsqlTest.cs
  test/EFCore.PG.FunctionalTests/Query/CharacterQueryNpgsqlTest.cs
  test/EFCore.PG.FunctionalTests/Query/CompatibilityQueryNpgsqlTest.cs
  test/EFCore.PG.FunctionalTests/Query/CompiledQueryNpgsqlTest.cs
  test/EFCore.PG.FunctionalTests/Query/DbFunctionsNpgsqlTest.cs
  test/EFCore.PG.FunctionalTests/Query/FiltersInheritanceNpgsqlTest.cs
  test/EFCore.PG.FunctionalTests/Query/FiltersNpgsqlTest.cs
  test/EFCore.PG.FunctionalTests/Query/GearsOfWarFromSqlQueryNpgsqlTest.cs
  test/EFCore.PG.FunctionalTests/Query/GearsOfWarQueryNpgsqlTest.cs
  test/EFCore.PG.FunctionalTests/Query/IncludeNpgsqlTest.cs
  test/EFCore.PG.FunctionalTests/Query/IncludeOneToOneNpgsqlTest.cs
  test/EFCore.PG.FunctionalTests/Query/MappingQueryNpgsqlTest.cs
  test/EFCore.PG.FunctionalTests/Query/MathQueryTest.cs
  test/EFCore.PG.FunctionalTests/Query/NavigationTest.cs
  test/EFCore.PG.FunctionalTests/Query/NetworkQueryNpgsqlTest.cs
  test/EFCore.PG.FunctionalTests/Query/NullSemanticsQueryNpgsqlTest.cs
  test/EFCore.PG.FunctionalTests/Query/QueryBugTest.cs
  test/EFCore.PG.FunctionalTests/Query/QueryFilterFuncletizationNpgsqlTest.cs
  test/EFCore.PG.FunctionalTests/Query/QueryNavigationsNpgsqlTest.cs
  test/EFCore.PG.FunctionalTests/Query/QueryTaggingNpgsqlTest.cs
  test/EFCore.PG.FunctionalTests/Query/SimpleQueryNpgsqlTest.Functions.cs
  test/EFCore.PG.FunctionalTests/Query/SpatialQueryNpgsqlGeographyTest.cs
  test/EFCore.PG.FunctionalTests/Query/SpatialQueryNpgsqlGeometryTest.cs
  test/EFCore.PG.FunctionalTests/Query/UdfDbFunctionNpgsqlTests.cs
  test/EFCore.PG.FunctionalTests/Scaffolding/NpgsqlDatabaseModelFactoryTest.cs
  test/EFCore.PG.FunctionalTests/SystemColumnTest.cs
  test/EFCore.PG.FunctionalTests/TestUtilities/NpgsqlDatabaseCleaner.cs
  test/EFCore.PG.FunctionalTests/TestUtilities/NpgsqlTestStore.cs
  test/EFCore.PG.FunctionalTests/TestUtilities/TestNpgsqlConnection.cs
  test/EFCore.PG.FunctionalTests/TestUtilities/TestNpgsqlRetryingExecutionStrategy.cs
  test/EFCore.PG.FunctionalTests/TestUtilities/TestRelationalCommandBuilderFactory.cs
  test/EFCore.PG.FunctionalTests/TestUtilities/TestRelationalTransaction.cs
  test/EFCore.PG.FunctionalTests/TestUtilities/Xunit/MinimumPostgresVersionAttribute.cs
  test/EFCore.PG.FunctionalTests/UpdatesNpgsqlTest.cs
Labels: refactor

#788 Format date/time literals using invariant culture
  EFCore.PG.sln.DotSettings
  src/EFCore.PG/Storage/Internal/Mapping/NpgsqlDateTimeTypeMappings.cs
Labels: bug

#792 Add support for unlogged tables
  EFCore.PG.sln.DotSettings
  src/EFCore.PG/Design/Internal/NpgsqlAnnotationCodeGenerator.cs
  src/EFCore.PG/Extensions/NpgsqlEntityTypeBuilderExtensions.cs
  src/EFCore.PG/Metadata/INpgsqlEntityTypeAnnotations.cs
  src/EFCore.PG/Metadata/Internal/NpgsqlAnnotationNames.cs
  src/EFCore.PG/Metadata/NpgsqlEntityTypeAnnotations.cs
  src/EFCore.PG/Migrations/Internal/NpgsqlMigrationsAnnotationProvider.cs
  src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs
  test/EFCore.PG.FunctionalTests/NpgsqlMigrationSqlGeneratorTest.cs
Labels: enhancement
