Repository npgsql/efcore.pg, pull requests merged in 2019-02, with the labels that each got.

#821 Remove non-generic Npgsql-specific HasIndex extension method
  src/EFCore.PG/Extensions/NpgsqlEntityTypeBuilderExtensions.cs
Labels: breaking change

#822 Update CI for PostgreSQL 11.1, PostGIS 2.5.1
  .appveyor.yml
  .build/setup_appveyor.ps1
Labels: test

#753 Implement DbFunctions extensions for websearch_to_tsquery (#629)
  QueryBaseline.cs
  src/EFCore.PG/Extensions/NpgsqlFullTextSearchDbFunctionsExtensions.cs
  src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlFullTextSearchMethodTranslator.cs
  test/EFCore.PG.FunctionalTests/Query/FullTextSearchDbFunctionsNpgsqlTest.cs
Labels: enhancement
