Repository npgsql/efcore.pg, pull requests merged in 2019-10, with the labels that each got.

#1065 Update repository and project urls
  Directory.Build.props
Labels: infrastructure

#1063 Add `IsNpgsql` extension method to EF's MigrationBuilder
  src/EFCore.PG/Migrations/NpgsqlMigrationBuilderExtensions.cs
  test/EFCore.PG.Tests/NpgsqlMigrationBuilderTest.cs
Labels: enhancement

#1083 Update repository and project urls to match new repo name
  Directory.Build.props
Labels: infrastructure

#1092 Use PERFORM within PL/pgSQL block to discard result
  src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs
  test/EFCore.PG.FunctionalTests/NpgsqlMigrationSqlGeneratorTest.cs
Labels: bug

#1068 Setup GitHub Actions v1
  .appveyor.yml
  .build/build-docker.sh
  .build/docker/Dockerfile
  .build/docker/initdb-npgsql.sh
  .build/setup_appveyor.ps1
  .build/setup_postgres.ps1
  .github/workflows/build.yml
  azure-pipelines.yml
  bump.sh
  src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlStringMethodTranslator.cs
  test/EFCore.PG.FunctionalTests/Query/FunkyDataQueryNpgsqlTest.cs
Labels: infrastructure
